name: CI - BankFlow QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Instalar dependências
        run: npm install

      - name: Resetar banco
        run: node scripts/reset-db.js

      - name: Subir API
        run: |
          nohup npm start > server.log 2>&1 &

      - name: Aguardar API iniciar
        run: |
          for i in {1..20}; do
            if curl -f http://localhost:3000/ >/dev/null 2>&1; then
              echo "API iniciada!"
              exit 0
            fi
            sleep 1
          done

          echo "A API não iniciou."
          cat server.log
          exit 1

      - name: Rodar testes automatizados
        run: npm test --ignore-scripts

      - name: Publicar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/newman/report.html